version: '3.8'
services:
  openhands-app:
    image: docker.all-hands.dev/all-hands-ai/openhands:0.38
    container_name: openhands-app
    tty: true
    stdin_open: true
    pull_policy: always
    environment:
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.38-nikolaik
      - LOG_ALL_EVENTS=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.openhands-state:/.openhands-state
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
